# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    # Use ["main", "master"] for CI only on the default branch.
    # Use ["**"] for CI on all branches.
    branches: ["main", "master"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # Update this as needed:
        # Common platforms: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["macos-latest"]
        python-version: ["3.11", "3.12"]

    # Linux only by default. Use ${{ matrix.os }} for other OSes.
    runs-on: ${{ matrix.os }}

    steps:
      # Generally following uv docs:
      # https://docs.astral.sh/uv/guides/integration/github/

      - name: Checkout (official GitHub action)
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          # Important for versioning plugins:
          fetch-depth: 0

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6
        with:
          # Update this as needed:
          version: "0.8.8"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Set up Python (using uv)
        run: uv python install

      # Alternately can use the official Python action:
      # - name: Set up Python (using actions/setup-python)
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - name: Install all dependencies
        run: uv sync --all-extras

      - name: Ruff check
        run: uv run ruff check src tests
      - name: MyPy
        run: uv run mypy src tests
